### PR TITLE
Add validation for region inside KMS ARN

### PR DESCRIPTION
**Pull request by cknowles**
Fixes https://github.com/kubernetes-incubator/kube-aws/issues/1041

### CODE REVIEW

**Comment by mumoshu** [comment]
@c-knowles Would you mind rebasing?

**Comment by c-knowles** [comment]
@mumoshu yep will do.

**Comment by c-knowles** [comment]
@mumoshu done

**Comment by c-knowles** [comment]
Will do the others once this is merged since they hit the same config_test.go file and will conflict.

**Pull request merged**
