### PR TITLE
Remove danielfm from OWNERS and SECURITY_CONTACTS

### PR DESCRIPTION
**Pull request by danielfm**
Unfortunately, I've been working for a different company for the past couple of years in which I no longer use Kubernetes in AWS, so I became quite outdated with how things are progressing in this project. For this reason, it is with great sadness that I'm stepping down as one of the maintainers of kube-aws. :cry: 

I thank each of the current - and past - maintainers for the patience and opportunity for letting me help you a little with this great project, and I'm sure it stays in good hands.

See you! :smile:

### CODE REVIEW

**Comment by dominicgunn** [comment]
Sad to see you go! Best of luck & thanks for the contributions.

**Comment by jorge07** [comment]
Thanks for all the work done this years

**Comment by mumoshu** [comment]
@danielfm It has been a great pleasure working with you!

**Comment by danielfm** [comment]
@mumoshu right back at you!

**Pull request merged**
