### PR TITLE
feat: Option to provide existing private keys.

### PR DESCRIPTION
**Pull request by dominicgunn**
## Changes

Allow users to provide their own private keys when generating credentials through `kube-aws render credentials`.

This patch was paramount for my team to be able to upgrade from kube-aws 10.1 to kube-aws 12.2. It allowed us to use our existing clusters certificates and upgrade in a smooth fashion.

### CODE REVIEW

**Comment by DominicGunn** [comment]
@k8s-ci-robot "I signed it!"

**Comment by davidmccormick** [comment]
Thanks Dominic!
/lgtm

**Comment by davidmccormick** [comment]
Please can you also PR this feature to the master branch?  Otherwise this functionality will be lost when 0.13 is released! 🙏

**Comment by davidmccormick** [comment]
@DominicGunn  Many thanks for your contribution!

**Comment by DominicGunn** [comment]
Thanks for the merge, PR for master coming right up

**Pull request merged**
